import './globals.css'

import NavBar from './ui/navbar'
import { Roboto } from 'next/font/google'
import SideNav from './ui/sidenav'
import YouTubePlayer from './ui/results/YouTubePlayer'

const roboto = Roboto({ subsets: ['latin'], weight: ['400', '500'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={roboto.className}>
        <NavBar />
        <div className="flex">
          {/* <YouTubePlayer /> */}
          {children}
        </div>
      </body>
    </html>
  )
}
