import './globals.css'

import NavBar from './ui/navbar'
import { Roboto } from 'next/font/google'
import SideNav from './ui/sidenav'

const roboto = Roboto({ subsets: ['latin'], weight: ['400', '500'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={roboto.className}>
        <NavBar />
        <div className="flex">
          <div className="flex-none w-60">
            <SideNav />
          </div>
          <div className="w-full pt-6 bg-test">{children}</div>
        </div>
      </body>
    </html>
  )
}
